"""Generate MSVC linker pragmas that forward every export of a System32 DLL to the real one.

Usage: python gen_forwarders.py <dllname> <out_header>
"""
import struct
import sys

name, out = sys.argv[1], sys.argv[2]
B = chr(92)
data = open(f"C:{B}Windows{B}System32{B}{name}.dll", "rb").read()
pe = struct.unpack_from("<I", data, 0x3C)[0]
nsec = struct.unpack_from("<H", data, pe + 6)[0]
optsz = struct.unpack_from("<H", data, pe + 20)[0]
opt = pe + 24
secs = [struct.unpack_from("<IIII", data, opt + optsz + i * 40 + 8) for i in range(nsec)]


def off(rva):
    for vsize, va, rsize, rptr in secs:
        if va <= rva < va + max(vsize, rsize):
            return rva - va + rptr
    raise ValueError(hex(rva))


exp_rva = struct.unpack_from("<I", data, opt + 112)[0]
e = off(exp_rva)
base, nfuncs, nnames, funcs, names_rva, ords = struct.unpack_from("<IIIIII", data, e + 16)
by_ordinal = {}
for i in range(nnames):
    nrva = struct.unpack_from("<I", data, off(names_rva) + 4 * i)[0]
    ordinal = struct.unpack_from("<H", data, off(ords) + 2 * i)[0] + base
    noff = off(nrva)
    by_ordinal[ordinal] = data[noff:data.index(b"\0", noff)].decode()

target = f"C:{B*2}Windows{B*2}System32{B*2}{name}"
lines = [f"// Generated by gen_forwarders.py from System32{B}{name}.dll: forward every export to the real DLL.",
         "#pragma once"]
for i in range(nfuncs):
    if struct.unpack_from("<I", data, off(funcs) + 4 * i)[0] == 0:
        continue
    ordinal = i + base
    if ordinal in by_ordinal:
        fn = by_ordinal[ordinal]
        lines.append(f'#pragma comment(linker, "/export:{fn}={target}.{fn},@{ordinal}")')
    else:
        lines.append(f'#pragma comment(linker, "/export:__ord{ordinal}={target}.#{ordinal},@{ordinal},NONAME")')
open(out, "w").write("\n".join(lines) + "\n")
print(f"{name}: {len(lines) - 2} exports")
